# Generated by Django 5.2.2 on 2026-06-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoneyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(db_index=True)),
                ("path", models.CharField(max_length=2048)),
                ("method", models.CharField(max_length=8)),
                ("headers", models.JSONField()),
                ("body", models.JSONField(blank=True, null=True)),
                ("ja3_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.TextField()),
                (
                    "decoy_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("env", "Env"),
                            ("wpAdmin", "WP Admin"),
                            ("api", "API"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("enriched", models.BooleanField(default=False)),
                (
                    "attacker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="profiles.attackerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip", "timestamp"], name="events_hone_ip_a9dc81_idx"
                    )
                ],
            },
        ),
    ]
