# Generated by Django 5.2.2 on 2026-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_honeyevent_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeyevent',
            name='decoy_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('env', 'Env'), ('wpAdmin', 'WP Admin'), ('api', 'API'), ('canary', 'Canary'), ('custom', 'Custom')], max_length=50),
        ),
    ]
