# Generated by Django 5.2.2 on 2026-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("condition", models.JSONField()),
                (
                    "notifier_type",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notifier_config", models.JSONField()),
                ("enabled", models.BooleanField(default=True)),
                ("last_fired", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
