# Generated by Django 5.2.2 on 2026-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThreatFeedEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("abuseipdb", "AbuseIPDB"),
                            ("virustotal", "VirusTotal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence", models.SmallIntegerField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-expires_at"],
            },
        ),
    ]
