# Generated by Django 5.2.2 on 2026-06-13 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanaryToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("url", "URL"),
                            ("email", "Email"),
                            ("dns", "DNS"),
                            ("aws_key", "AWS Key"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("triggered", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("trigger_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canary_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
            },
        ),
    ]
