# Generated by Django 5.2.2 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecoyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_pattern', models.CharField(max_length=500)),
                ('is_regex', models.BooleanField(default=False)),
                ('decoy_type', models.CharField(choices=[('admin', 'Admin'), ('env', 'Env'), ('wpAdmin', 'WP Admin'), ('api', 'API'), ('custom', 'Custom')], max_length=50)),
                ('response_template', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority', 'path_pattern'],
            },
        ),
    ]
