# Generated by Django 5.2.2 on 2026-06-17 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_decoyroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='canarytoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
